[package]
name = "esocietyhere/datastore2"
description = "A wally package of Kampfkarren's DataStore2 with buildthomas' MockDataStoreService"
authors = ["Kampfkarren"]
license = "MIT"
version = "1.4.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
MockDataStoreService = "buildthomas/mockdatastoreservice@1.0.3"